In [1]:
import pandas as pd
import eikon as ek

In [2]:
company_data=pd.read_csv("company_CUS_gvkey.csv")
company_data.head()

  ticker                       comnam    cusip8  gvkey Refinitive_CUSIP
0    AAL  AMERICAN AIRLINES GROUP INC  02376R10   1045        02376R102
1    PNW   PINNACLE WEST CAPITAL CORP  72348410   1075        723484101
2    ABT          ABBOTT LABORATORIES  00282410   1078        002824100
3    AMD   ADVANCED MICRO DEVICES INC  00790310   1161        007903107
4    AET                AETNA INC NEW  00817Y10   1177        00817Y108

In [3]:
CUSIP_data=company_data[company_data["Refinitive_CUSIP"]!="error"]["Refinitive_CUSIP"]

get data

In [4]:
ek.set_app_key('1c5f178448d04f94a0fa7c5bbf8507be61125800')

In [6]:
'''
ek_margins_returns = [
 'TR.F.GROSSPROFMARG',# Gross margin is net sales less the cost of goods sold (COGS). In other words, it's the amount of money a company retains after incurring the direct costs associated with producing the goods it sells and the services it provides.
 'TR.F.EBITDAMARGPCT',# The EBITDA margin is a measure of a company's operating profit as a percentage of its revenue. The acronym EBITDA stands for earnings before interest, taxes, depreciation, and amortization. Knowing the EBITDA margin allows for a comparison of one company's real performance to others in its industry.
 'TR.F.OPMARGPCT',#
 'TR.F.NETMARGPCT',#
 'TR.F.RETURNAVGCOMEQPCT',#
 'TR.F.RETURNINVSTCAPPCT',#
 'TR.PriceToBVPerShare',# Price to book value per share is calculated by dividing the company's latest closing price by its book value per share.
 'TR.PE',#
 'TR.PriceToSalesPerShare',# PriceToSalesPerShare, Price to sales per share calculated by dividing the company's market capitalization by its total sales (Price/Sales LTM).
 'TR.NAICSSectorCode',# GICS is a four-tiered, hierarchical industry classification system. Companies are classified quantitatively and qualitatively.
 'TR.NAICSSubsectorCode',# 
 'TR.NAICSIndustryGroupCode',#
 'TR.NAICSInternationalIndustryCode',#
 'TR.NAICSNationalIndustryCode',#
 "TR.CompanyMarketCap(ShType=DEF)",# The market capitalization sometimes referred as Marketcap, is the value of a publicly listed company.
 "TR.CompanyNumEmploy"#
]
'''

ek_margins_returns = [
 'TR.PriceToBVPerShare',# Price to book value per share is calculated by dividing the company's latest closing price by its book value per share.
 "TR.CompanyNumEmploy",#
 'TR.F.RETURNINVSTCAPPCT',
 "TR.F.ReturnAvgTotAssetsPctTTM(Period=FI0)"
]

str_asofdate = '2022-01-01'

In [7]:
firmdat, err =ek.get_data(list(CUSIP_data), ek_margins_returns,parameters={'SDate':str_asofdate,'Scale':'6','Period':'FY0'})

In [8]:
err

[{'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 7},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 7},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 30},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 30},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 37},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 37},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 43},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 43},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 48},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 48},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 110},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 110},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 134},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 134},
 {'code': 416,
  'col': 1,
  'message': "Unable to collect data for the field 'TR.PriceToBVPerShare' and some specific identifier(s).",
  'row': 149},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 149},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 149},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 152},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 152},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 158},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 158},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 164},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 164},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 170},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 170},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 175},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 175},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 188},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 188},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 210},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 210},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 222},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 222},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 223},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 223},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 243},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 243},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 249},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 249},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 270},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 270},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 275},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 275},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 280},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 280},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 282},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 282},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 285},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 285},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 301},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 301},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 302},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 302},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 318},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 318},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 325},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 325},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 326},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 326},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 334},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 334},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 349},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 349},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 354},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 354},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 355},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 355},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 358},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 358},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 359},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 359},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 360},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 360},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 372},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 372},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 382},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 382},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 384},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 384},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 398},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 398},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 422},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 422},
 {'code': 416,
  'col': 1,
  'message': "Unable to collect data for the field 'TR.PriceToBVPerShare' and some specific identifier(s).",
  'row': 429},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 432},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 432},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 435},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 435},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 447},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 447},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 452},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 452},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 455},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 455},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 461},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 461},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 464},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 464},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 469},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 469},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 470},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 470},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 496},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 496},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 497},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 497},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 504},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 504},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 519},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 519},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 521},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 521},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 523},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 523},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 543},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 543},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 545},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 545},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 551},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 551},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 568},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 568},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 582},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 582},
 {'code': 416,
  'col': 3,
  'message': "Unable to collect data for the field 'TR.F.ReturnInvstCapPct' and some specific identifier(s).",
  'row': 587},
 {'code': 416,
  'col': 4,
  'message': "Unable to collect data for the field 'TR.F.ReturnAvgTotAssetsPctTTM' and some specific identifier(s).",
  'row': 587}]

In [9]:
firmdat

,Instrument,Price To Book Value Per Share (Daily Time Series Ratio),Number of Employees,Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
0,02376R102,-1.563627,102700,NaN,-4.937124
1,723484101,1.313080,88,6.007651,2.610904
2,002824100,7.229932,109000,9.914621,10.173763
3,007903107,24.440415,12600,54.464218,43.672975
4,00817Y108,NaN,47950,6.918382,6.605174
...,...,...,...,...,...
590,98212B103,NaN,590,5.644184,-9.800784
591,34964C106,4.750213,27505,12.402273,10.574237
592,98419M100,6.990487,16700,5.688523,5.566600
593,896945201,4.742451,2738,NaN,-6.778087
594,94946T106,NaN,12000,9.949082,4.819112

In [10]:
firmdat=firmdat.rename(columns={"Instrument": "Refinitive_CUSIP"})

In [11]:
result_data=company_data.merge(firmdat,how="left")
result_data

,ticker,comnam,cusip8,gvkey,Refinitive_CUSIP,Price To Book Value Per Share (Daily Time Series Ratio),Number of Employees,Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
0,AAL,AMERICAN AIRLINES GROUP INC,02376R10,1045,02376R102,-1.563627,102700,NaN,-4.937124
1,PNW,PINNACLE WEST CAPITAL CORP,72348410,1075,723484101,1.313080,88,6.007651,2.610904
2,ABT,ABBOTT LABORATORIES,00282410,1078,002824100,7.229932,109000,9.914621,10.173763
3,AMD,ADVANCED MICRO DEVICES INC,00790310,1161,007903107,24.440415,12600,54.464218,43.672975
4,AET,AETNA INC NEW,00817Y10,1177,00817Y108,NaN,47950,6.918382,6.605174
...,...,...,...,...,...,...,...,...,...
718,TRIP,TRIPADVISOR INC,89694520,199356,896945201,4.742451,2738,NaN,-6.778087
719,CBG,C B RICHARD ELLIS GROUP INC,12497T10,260774,error,NaN,<NA>,NaN,NaN
720,WCG,WELLCARE HEALTH PLANS INC,94946T10,260778,94946T106,NaN,12000,9.949082,4.819112
721,LYB,LYONDELLBASELL INDUSTRIES N V,N5374510,294524,error,NaN,<NA>,NaN,NaN
722,ALLE,ALLEGION PLC,G0176J10,316056,error,NaN,<NA>,NaN,NaN

In [14]:
result_data.to_csv("company_refinitiv_detail_data_with_assets.csv",index=False)

In [15]:
pd.read_csv("company_refinitiv_detail_data_with_assets.csv")

,ticker,comnam,cusip8,gvkey,Refinitive_CUSIP,Price To Book Value Per Share (Daily Time Series Ratio),Number of Employees,Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
0,AAL,AMERICAN AIRLINES GROUP INC,02376R10,1045,02376R102,-1.563627,102700.0,NaN,-4.937124
1,PNW,PINNACLE WEST CAPITAL CORP,72348410,1075,723484101,1.313080,88.0,6.007651,2.610904
2,ABT,ABBOTT LABORATORIES,00282410,1078,002824100,7.229932,109000.0,9.914621,10.173763
3,AMD,ADVANCED MICRO DEVICES INC,00790310,1161,007903107,24.440415,12600.0,54.464218,43.672975
4,AET,AETNA INC NEW,00817Y10,1177,00817Y108,NaN,47950.0,6.918382,6.605174
...,...,...,...,...,...,...,...,...,...
718,TRIP,TRIPADVISOR INC,89694520,199356,896945201,4.742451,2738.0,NaN,-6.778087
719,CBG,C B RICHARD ELLIS GROUP INC,12497T10,260774,error,NaN,NaN,NaN,NaN
720,WCG,WELLCARE HEALTH PLANS INC,94946T10,260778,94946T106,NaN,12000.0,9.949082,4.819112
721,LYB,LYONDELLBASELL INDUSTRIES N V,N5374510,294524,error,NaN,NaN,NaN,NaN
722,ALLE,ALLEGION PLC,G0176J10,316056,error,NaN,NaN,NaN,NaN