In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd gdrive/MyDrive/Colab\ Notebooks/capstone/Yuechen-Indeed-capstone-data

Mounted at /content/gdrive
/content/gdrive/MyDrive/Colab Notebooks/capstone/Yuechen-Indeed-capstone-data

## Load data

In [3]:
data=pd.read_csv("add10-1.csv")

In [4]:
data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag
0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936,1
1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430,1
2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410,-1
3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765,1
4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1

In [5]:
finace_data=pd.read_csv("company_refinitiv_detail_data_with_assets.csv")
finace_data_use=finace_data[["gvkey","Price To Book Value Per Share (Daily Time Series Ratio)","Return on Invested Capital - %","Return on Average Total Assets - %, TTM"]]
finace_data_use

,gvkey,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
0,1045,-1.563627,NaN,-4.937124
1,1075,1.313080,6.007651,2.610904
2,1078,7.229932,9.914621,10.173763
3,1161,24.440415,54.464218,43.672975
4,1177,NaN,6.918382,6.605174
...,...,...,...,...
718,199356,4.742451,NaN,-6.778087
719,260774,NaN,NaN,NaN
720,260778,NaN,9.949082,4.819112
721,294524,NaN,NaN,NaN
722,316056,NaN,NaN,NaN

In [6]:
ana_data=data.merge(finace_data_use,on="gvkey")
ana_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936,1,-1.563627,NaN,-4.937124
1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430,1,-1.563627,NaN,-4.937124
2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410,-1,-1.563627,NaN,-4.937124
3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765,1,-1.563627,NaN,-4.937124
4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576,1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

Price To Book Value Per Share (Daily Time Series Ratio)

In [7]:
#
culture_data=ana_data[ana_data["culture"]>0.5]
culture_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
619,American Airlines,Executive Platnium Customer Service Representive,"Salem, NC",4.0,Productive and fast-paced with incredible bene...,"In a typical work day, one can expect various ...",2020-05-24,1045,21020.0,NEGATIVE,0.966065,0.506180,0.511126,0.511564,0.512915,-1,-1.563627,NaN,-4.937124
899,American Airlines,International Resolution Agent,"Cary, NC",4.0,Great Flexibility,The ability to trade shifts and get extra time...,2020-01-05,1045,21020.0,POSITIVE,0.999868,0.500417,0.503774,0.500978,0.503656,1,-1.563627,NaN,-4.937124
1339,American Airlines,Executive Platinum Client Specialist,"Fort Worth, TX",4.0,American Airline,Establishes long term career path that allows ...,2019-05-21,1045,21020.0,POSITIVE,0.999801,0.503781,0.504985,0.503245,0.505096,1,-1.563627,NaN,-4.937124
2226,American Airlines,SKYCAP,"Orange County, CA",5.0,fun and exciting work place,Provide check in services at curbside for Amer...,2018-02-12,1045,21020.0,POSITIVE,0.867347,0.508332,0.509314,0.507959,0.511954,1,-1.563627,NaN,-4.937124
2273,American Airlines,Customer Care Manager-Global Reservations,"Salem, NC",4.0,Typical Day,Always engaged with your team to provide the '...,2018-01-15,1045,21020.0,POSITIVE,0.999020,0.500210,0.503872,0.500683,0.506128,1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

In [8]:
culture_data["Price To Book Value Per Share (Daily Time Series Ratio)"].dropna()

619       -1.563627
899       -1.563627
1339      -1.563627
2226      -1.563627
2273      -1.563627
             ...
2325055    4.742451
2325056    4.742451
2325057    4.742451
2325058    4.742451
2325059    4.742451
Name: Price To Book Value Per Share (Daily Time Series Ratio), Length: 510584, dtype: float64

In [9]:
#
compensation_data=ana_data[ana_data["compensation"]>0.5]
compensation_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
453,American Airlines,Flight Attendant,"Fort Worth, TX",4.0,"Not a job, but a way of life","It's a rewarding job, in that you help custome...",2020-09-26,1045,21020.0,POSITIVE,0.999885,0.495480,0.500283,0.495778,0.497858,1,-1.563627,NaN,-4.937124
619,American Airlines,Executive Platnium Customer Service Representive,"Salem, NC",4.0,Productive and fast-paced with incredible bene...,"In a typical work day, one can expect various ...",2020-05-24,1045,21020.0,NEGATIVE,0.966065,0.506180,0.511126,0.511564,0.512915,-1,-1.563627,NaN,-4.937124
899,American Airlines,International Resolution Agent,"Cary, NC",4.0,Great Flexibility,The ability to trade shifts and get extra time...,2020-01-05,1045,21020.0,POSITIVE,0.999868,0.500417,0.503774,0.500978,0.503656,1,-1.563627,NaN,-4.937124
1339,American Airlines,Executive Platinum Client Specialist,"Fort Worth, TX",4.0,American Airline,Establishes long term career path that allows ...,2019-05-21,1045,21020.0,POSITIVE,0.999801,0.503781,0.504985,0.503245,0.505096,1,-1.563627,NaN,-4.937124
1497,American Airlines,Reservationist,"Fort Worth, TX",1.0,Poor environment,You get verbally abused by passengers calling ...,2019-03-05,1045,21020.0,NEGATIVE,0.995947,0.497723,0.502326,0.500233,0.501235,-1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

In [10]:
work_life_data=ana_data[ana_data["work life balance"]>0.5]
work_life_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
619,American Airlines,Executive Platnium Customer Service Representive,"Salem, NC",4.0,Productive and fast-paced with incredible bene...,"In a typical work day, one can expect various ...",2020-05-24,1045,21020.0,NEGATIVE,0.966065,0.506180,0.511126,0.511564,0.512915,-1,-1.563627,NaN,-4.937124
899,American Airlines,International Resolution Agent,"Cary, NC",4.0,Great Flexibility,The ability to trade shifts and get extra time...,2020-01-05,1045,21020.0,POSITIVE,0.999868,0.500417,0.503774,0.500978,0.503656,1,-1.563627,NaN,-4.937124
1339,American Airlines,Executive Platinum Client Specialist,"Fort Worth, TX",4.0,American Airline,Establishes long term career path that allows ...,2019-05-21,1045,21020.0,POSITIVE,0.999801,0.503781,0.504985,0.503245,0.505096,1,-1.563627,NaN,-4.937124
1497,American Airlines,Reservationist,"Fort Worth, TX",1.0,Poor environment,You get verbally abused by passengers calling ...,2019-03-05,1045,21020.0,NEGATIVE,0.995947,0.497723,0.502326,0.500233,0.501235,-1,-1.563627,NaN,-4.937124
2226,American Airlines,SKYCAP,"Orange County, CA",5.0,fun and exciting work place,Provide check in services at curbside for Amer...,2018-02-12,1045,21020.0,POSITIVE,0.867347,0.508332,0.509314,0.507959,0.511954,1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

In [11]:
career_opportunity_data=ana_data[ana_data["career opportunity"]>0.5]
career_opportunity_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
619,American Airlines,Executive Platnium Customer Service Representive,"Salem, NC",4.0,Productive and fast-paced with incredible bene...,"In a typical work day, one can expect various ...",2020-05-24,1045,21020.0,NEGATIVE,0.966065,0.506180,0.511126,0.511564,0.512915,-1,-1.563627,NaN,-4.937124
899,American Airlines,International Resolution Agent,"Cary, NC",4.0,Great Flexibility,The ability to trade shifts and get extra time...,2020-01-05,1045,21020.0,POSITIVE,0.999868,0.500417,0.503774,0.500978,0.503656,1,-1.563627,NaN,-4.937124
1339,American Airlines,Executive Platinum Client Specialist,"Fort Worth, TX",4.0,American Airline,Establishes long term career path that allows ...,2019-05-21,1045,21020.0,POSITIVE,0.999801,0.503781,0.504985,0.503245,0.505096,1,-1.563627,NaN,-4.937124
1497,American Airlines,Reservationist,"Fort Worth, TX",1.0,Poor environment,You get verbally abused by passengers calling ...,2019-03-05,1045,21020.0,NEGATIVE,0.995947,0.497723,0.502326,0.500233,0.501235,-1,-1.563627,NaN,-4.937124
1536,American Airlines,Java Spring Angular Developer,"Irving, TX",4.0,Produtive,Managing the DEVQAUATPROD environments with Hi...,2019-02-08,1045,21020.0,POSITIVE,0.993768,0.495634,0.500650,0.496867,0.503682,1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

T-tese:

In [12]:
culture_data[(culture_data["sen_flag"]==1)].loc[:,"Price To Book Value Per Share (Daily Time Series Ratio)"].dropna()

899       -1.563627
1339      -1.563627
2226      -1.563627
2273      -1.563627
2339      -1.563627
             ...
2325052    4.742451
2325054    4.742451
2325056    4.742451
2325058    4.742451
2325059    4.742451
Name: Price To Book Value Per Share (Daily Time Series Ratio), Length: 302068, dtype: float64

In [13]:
career_opportunity_data

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity,sen_flag,Price To Book Value Per Share (Daily Time Series Ratio),Return on Invested Capital - %,"Return on Average Total Assets - %, TTM"
619,American Airlines,Executive Platnium Customer Service Representive,"Salem, NC",4.0,Productive and fast-paced with incredible bene...,"In a typical work day, one can expect various ...",2020-05-24,1045,21020.0,NEGATIVE,0.966065,0.506180,0.511126,0.511564,0.512915,-1,-1.563627,NaN,-4.937124
899,American Airlines,International Resolution Agent,"Cary, NC",4.0,Great Flexibility,The ability to trade shifts and get extra time...,2020-01-05,1045,21020.0,POSITIVE,0.999868,0.500417,0.503774,0.500978,0.503656,1,-1.563627,NaN,-4.937124
1339,American Airlines,Executive Platinum Client Specialist,"Fort Worth, TX",4.0,American Airline,Establishes long term career path that allows ...,2019-05-21,1045,21020.0,POSITIVE,0.999801,0.503781,0.504985,0.503245,0.505096,1,-1.563627,NaN,-4.937124
1497,American Airlines,Reservationist,"Fort Worth, TX",1.0,Poor environment,You get verbally abused by passengers calling ...,2019-03-05,1045,21020.0,NEGATIVE,0.995947,0.497723,0.502326,0.500233,0.501235,-1,-1.563627,NaN,-4.937124
1536,American Airlines,Java Spring Angular Developer,"Irving, TX",4.0,Produtive,Managing the DEVQAUATPROD environments with Hi...,2019-02-08,1045,21020.0,POSITIVE,0.993768,0.495634,0.500650,0.496867,0.503682,1,-1.563627,NaN,-4.937124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734,1,NaN,NaN,NaN
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166,1,NaN,NaN,NaN
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586,1,NaN,NaN,NaN
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244,-1,NaN,NaN,NaN
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050,1,NaN,NaN,NaN

In [14]:
stats.ttest_ind(ana_data[(ana_data["sen_flag"]==1)].loc[:,"Price To Book Value Per Share (Daily Time Series Ratio)"].dropna(), ana_data[(ana_data["sen_flag"]==-1)].loc[:,"Price To Book Value Per Share (Daily Time Series Ratio)"].dropna())

NameError: ignored

In [16]:
label="Return on Invested Capital - %"

In [21]:
stats.ttest_ind(career_opportunity_data[(career_opportunity_data["sen_flag"]==1)].loc[:,label].dropna(), career_opportunity_data[(career_opportunity_data["sen_flag"]==-1)].loc[:,label].dropna())

Ttest_indResult(statistic=-11.445723202540224, pvalue=2.4964354816299988e-30)

In [ ]:
ana_data.loc[:,"Return on Average Total Assets - %, TTM"].dropna()

calculate

In [ ]:
culture_result=culture_data[["sen_flag","Price To Book Value Per Share (Daily Time Series Ratio)","Return on Invested Capital - %","Return on Average Total Assets - %, TTM"]].groupby("sen_flag").mean()
culture_result

In [ ]:
compensation_result=compensation_data[["sen_flag","Price To Book Value Per Share (Daily Time Series Ratio)","Return on Invested Capital - %","Return on Average Total Assets - %, TTM"]].groupby("sen_flag").mean()
compensation_result

In [ ]:
work_life_result=work_life_data[["sen_flag","Price To Book Value Per Share (Daily Time Series Ratio)","Return on Invested Capital - %","Return on Average Total Assets - %, TTM"]].groupby("sen_flag").mean()
work_life_result

In [ ]:
opp_result=career_opportunity_data[["sen_flag","Price To Book Value Per Share (Daily Time Series Ratio)","Return on Invested Capital - %","Return on Average Total Assets - %, TTM"]].groupby("sen_flag").mean()
opp_result

Price To Book Value

In [ ]:
culture_result.columns=["culture","culture_","culture__"]
compensation_result.columns=["compensation","compensation_","compensation__"]
work_life_result.columns=["work life","work life_","work life__"]
opp_result.columns=["opp_result","opp_result_","opp_result__"]

In [ ]:
book_value=pd.DataFrame([culture_result["culture"],compensation_result["compensation"],work_life_result["work life"],opp_result["opp_result"]]).T
book_value

In [ ]:
book_value=book_value.T
book_value["difference"]=book_value[-1]-book_value[1]
book_value

In [15]:
from scipy import stats

In [ ]:
stats.ttest_ind(book_value[-1], book_value[1])

In [ ]:
stats.ttest_ind(book_value[-1], book_value[0])

In [ ]:
stats.ttest_ind(book_value[0], book_value[1])

Return on Invest Captial

In [ ]:
return_cap_value=pd.DataFrame([culture_result["culture_"],compensation_result["compensation_"],work_life_result["work life_"],opp_result["opp_result_"]]).T
return_cap_value

In [ ]:
return_cap_value=return_cap_value.T
return_cap_value["difference"]=return_cap_value[-1]-return_cap_value[1]
return_cap_value

In [ ]:
stats.ttest_ind(return_cap_value[-1], return_cap_value[1])

In [ ]:
stats.ttest_ind(return_cap_value[-1], return_cap_value[0])

In [ ]:
stats.ttest_ind(return_cap_value[0], return_cap_value[1])

return on assets

In [ ]:
return_asset_value=pd.DataFrame([culture_result["culture__"],compensation_result["compensation__"],work_life_result["work life__"],opp_result["opp_result__"]]).T
return_asset_value

In [ ]:
return_asset_value=return_asset_value.T
return_asset_value["difference"]=return_asset_value[-1]-return_asset_value[1]
return_asset_value

In [ ]:
stats.ttest_ind(return_asset_value[1], return_asset_value[-1])

In [ ]:
stats.ttest_ind(return_asset_value[0], return_asset_value[-1])

In [ ]:
stats.ttest_ind(return_asset_value[0], return_asset_value[1])