In [2]:
import pandas as pd

In [4]:
df1=pd.read_csv("light-zero-shot/light-zero-shot-class-0.csv",header=None)
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936
1,1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430
2,2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410
3,3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765
4,4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271195,271195,Computer Science Corporation,Director is away on official business,"Bethesda, MD",4.0,Pretty Good,Enjoyed my 2 years with them at NGA. They are...,2013-11-12,3336,40125.0,POSITIVE,0.999150,0.481290,0.485870,0.484097,0.484710
271196,271196,Computer Science Corporation,Information Security System Technician,"San Antonio, TX",5.0,Very intelligent and career oriented indivuals,Monitor an Intrusion Detection System for the ...,2013-11-11,3336,40125.0,NEGATIVE,0.955710,0.479778,0.481291,0.479039,0.482531
271197,271197,Computer Science Corporation,IT Project Manager,"Annapolis Junction, Md.",3.0,Good place to work. Serious about the mission,CSC is a good place to work. They are serious ...,2013-11-10,3336,40125.0,POSITIVE,0.999801,0.480440,0.485495,0.480073,0.484896
271198,271198,Computer Science Corporation,Quality Assurance Technician,"Richmond, VA",3.0,Good place to work,Small company with very few openings. They are...,2013-10-30,3336,40125.0,NEGATIVE,0.974259,0.474954,0.479394,0.473450,0.476461
271199,271199,Computer Science Corporation,Executive Administrative Assistant,"Fort Hood, TX",3.0,"Great benefits, great pay. Management in 2005 ...",I worked for this company and left for Materni...,2013-10-29,3336,40125.0,NEGATIVE,0.999154,0.464769,0.467162,0.465611,0.466945

In [6]:
df2=pd.read_csv("light-zero-shot/light-zero-shot-class-271199.csv",header=None)
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,271199,Computer Science Corporation,Executive Administrative Assistant,"Fort Hood, TX",3.0,"Great benefits, great pay. Management in 2005 ...",I worked for this company and left for Materni...,2013-10-29,3336,40125.0,NEGATIVE,0.999154,0.481777,0.481805,0.483031,0.483640
1,271200,Computer Science Corporation,Communications Subsystem Engineer,"Lanham, MD",3.0,"Secured place to work, friendly people to work...",Great Project staff to work with. Open to sugg...,2013-10-25,3336,40125.0,POSITIVE,0.999269,0.482465,0.480440,0.482832,0.483786
2,271201,Computer Science Corporation,Logistics Coordinator,"Falls Church, VA",4.0,Overseas Contracting,Work with Various system worked 12HR days trul...,2013-10-23,3336,40125.0,POSITIVE,0.982095,0.498310,0.489464,0.495653,0.495048
3,271202,Computer Science Corporation,Customer Service Representative,"Barbourville, KY",3.0,Long,Makes for a long work day but enjoyed working ...,2013-10-22,3336,40125.0,POSITIVE,0.993015,0.500444,0.498390,0.500968,0.504701
4,271203,Computer Science Corporation,Field Service Technician,"Saint Paul, MN",3.0,Large corporation that loses sight of its most...,My day consisted of incident management and ha...,2013-10-22,3336,40125.0,NEGATIVE,0.997400,0.478859,0.479466,0.479904,0.480793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247795,518994,General Motors,Voice of the Customer Specialist,"Warren, MI",4.0,Great place to work.,Working at the General Motors Tech Center in W...,2016-04-04,5073,12369.0,POSITIVE,0.989432,0.490821,0.488383,0.489548,0.489056
247796,518995,General Motors,Process Engineer,"Moraine, OH",4.0,Great team to work with,The workers at General Motors are dedicated to...,2016-04-02,5073,12369.0,POSITIVE,0.999777,0.501519,0.498650,0.500196,0.502602
247797,518996,General Motors,Software Developer,"Austin, TX",4.0,Overall great company,Love the company and the opportunities that ar...,2016-04-01,5073,12369.0,POSITIVE,0.638599,0.485141,0.484601,0.486076,0.486241
247798,518997,General Motors,Welder/Assembler/Fork Truck Driver,"Swartz Creek, MI",5.0,"Great people, Great place to work",I was fortunate enough to work at 8 GM facilit...,2016-03-31,5073,12369.0,POSITIVE,0.999243,0.485607,0.485173,0.487323,0.486730
247799,518998,General Motors,Process Engineer,"Wentzville, MO",3.0,Productive - traditional manufacturing environ...,Poor Job work/life balance - average about one...,2016-03-31,5073,12369.0,POSITIVE,0.686433,0.498669,0.497182,0.496670,0.496965

In [8]:
df3=pd.read_csv("light-zero-shot/light-zero-shot-class-518998.csv",header=None)
df3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,518998,General Motors,Process Engineer,"Wentzville, MO",3.0,Productive - traditional manufacturing environ...,Poor Job work/life balance - average about one...,2016-03-31,5073,12369.0,POSITIVE,0.686433,0.438414,0.439305,0.440348,0.440458
1,518999,General Motors,EIT tool room,"Lansing, MI",5.0,People make the difference,Over the last 35 plus years I have found that ...,2016-03-29,5073,12369.0,POSITIVE,0.998088,0.464301,0.461072,0.466725,0.465334
2,519000,General Motors,Assembly Worker,"Warren, OH 44481",3.0,"Good place for some, but not for everyone","You will work from 40 to 48 hours (5 to 6, 8-h...",2016-03-25,5073,12369.0,POSITIVE,0.823553,0.450303,0.450336,0.453895,0.452410
3,519001,General Motors,Customer service Representative,"Austin, TX",4.0,Hard to keep up with metrics.,"A typical day at work is really easy, relaxed,...",2016-03-24,5073,12369.0,NEGATIVE,0.986446,0.456915,0.456504,0.461050,0.458991
4,519002,General Motors,Technology Team Manager,"Detroit, MI",4.0,Great Place to Work,The environment now is better than it ever was...,2016-03-24,5073,12369.0,POSITIVE,0.999676,0.453236,0.450364,0.457638,0.455549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80995,599993,The Home Depot,Cashier,"Cincinnati, Oh",4.0,"Management really cares about employees, and c...",I really enjoy working at Home Depot. The frie...,2013-07-27,5680,66181.0,POSITIVE,0.999555,0.457584,0.456327,0.460242,0.458175
80996,599994,The Home Depot,Sales Consultant,newark ohio,4.0,advancement opportunites,good place to work.....did not have issues wit...,2013-07-27,5680,66181.0,POSITIVE,0.999149,0.449610,0.445815,0.449746,0.448027
80997,599995,The Home Depot,Cashier,"Jonesboro, AR",5.0,Great place to work.,"I really enjoyed working there, it felt like a...",2013-07-27,5680,66181.0,POSITIVE,0.999798,0.449901,0.447492,0.454566,0.452829
80998,599996,The Home Depot,Paint Specialist and Sales Associate,"Wichita Falls, TX",4.0,"Good place, too much drama.",Was an ok place to work for. There was a littl...,2013-07-27,5680,66181.0,POSITIVE,0.999279,0.464810,0.464053,0.466191,0.465092
80999,599997,The Home Depot,Cashier,"Rochester, NY",3.0,"Not a bad place, but not great either",They would work a little bit with my visitatio...,2013-07-27,5680,66181.0,POSITIVE,0.997789,0.443531,0.445199,0.449541,0.447897

In [9]:
df4=pd.read_csv("light-zero-shot/light-zero-shot-class-600000.csv",header=None)
df4

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,600000,The Home Depot,Front End Operations,"Hackettstown, NJ",4.0,Good Job,Employee morale is very low due to the inabili...,2013-07-26,5680,66181.0,NEGATIVE,0.999758,0.500127,0.500439,0.504501,0.502394
1,600001,The Home Depot,supervisor-key carrier,"clovis, CA",3.0,you can take your career far with hard work an...,home depot is a great place for young people w...,2013-07-26,5680,66181.0,POSITIVE,0.999623,0.481500,0.477048,0.483981,0.482318
2,600002,The Home Depot,Cashier,"Port Saint Lucie, FL",3.0,Nice place to work,Working as a cashier was easy. Occasionally yo...,2013-07-26,5680,66181.0,POSITIVE,0.995289,0.491286,0.491507,0.495955,0.495154
3,600003,The Home Depot,Front End Supervisor/ Sales Assoc,"Waco, TX",4.0,Productive and interesting work place with man...,A great place to work and grow personally as w...,2013-07-26,5680,66181.0,POSITIVE,0.999873,0.471621,0.473716,0.478027,0.475657
4,600004,The Home Depot,Lumber associate,"Lawrenceville hwy, ga",5.0,Work to play,A typical day in home depot consist of custome...,2013-07-26,5680,66181.0,POSITIVE,0.996358,0.494426,0.494298,0.497410,0.497217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399795,999795,Nordstrom,Sales Representative,"Garden City, NY",5.0,Itâ€™s retail...,Nordstrom is probably the best place to work r...,2019-11-14,7922,57817.0,POSITIVE,0.999628,0.472221,0.471775,0.473494,0.472544
399796,999796,Nordstrom,Loss Prevention Service Ambassador,"Chandler, AZ",5.0,Great place,Great place with plenty of room for advancemen...,2019-11-14,7922,57817.0,POSITIVE,0.999007,0.473850,0.473664,0.478911,0.477048
399797,999797,Nordstrom,Barista,"Bloomington, MN (MOA)",5.0,Satisfying work,As much as I love being a Barista the experien...,2019-11-13,7922,57817.0,POSITIVE,0.999880,0.480616,0.477550,0.484608,0.483207
399798,999798,Nordstrom,Retail Cashier,"Boston, MA",1.0,Poor culture,Uptight and snooty. Overall people were arroga...,2019-11-13,7922,57817.0,NEGATIVE,0.998430,0.477680,0.477971,0.480847,0.481261
399799,999799,Nordstrom,Logistics Staff Member,"Glen Allen, VA",2.0,This is a fashion retail store,If you are interested in a fashion career this...,2019-11-13,7922,57817.0,POSITIVE,0.974132,0.475783,0.477382,0.482024,0.479648

In [10]:
df5=pd.read_csv("light-zero-shot/light-zero-shot-class-999799.csv",header=None)
df5

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,999799,Nordstrom,Logistics Staff Member,"Glen Allen, VA",2.0,This is a fashion retail store,If you are interested in a fashion career this...,2019-11-13,7922,57817.0,POSITIVE,0.974132,0.505799,0.506489,0.507984,0.506175
1,999800,Nordstrom,Line Cook,"Cherry Hill, NJ",5.0,Great benefits and room to grow.,Great company well trained and experienced ...,2019-11-13,7922,57817.0,POSITIVE,0.998537,0.520153,0.519846,0.522072,0.518399
2,999801,Nordstrom,Sales Associate shoes,"Arcadia, CA",1.0,Poor management,Leaders shows favoritism to long term employee...,2019-11-13,7922,57817.0,NEGATIVE,0.998343,0.524145,0.523934,0.527962,0.524204
3,999802,Nordstrom,Service Ex,"Seattle, WA",5.0,Productive and Fast paced work enviroment,A typical day as a Service Experience Represen...,2019-11-13,7922,57817.0,POSITIVE,0.725524,0.528640,0.528105,0.528832,0.529303
4,999803,Nordstrom,Service Experience Specialist,"Colorado Springs, CO",1.0,"Pay is awful and so many employees slack off, ...",Favoritism seems to get you promoted here. It ...,2019-11-13,7922,57817.0,NEGATIVE,0.997976,0.512355,0.513244,0.516262,0.513177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,999994,Nordstrom,SALES ASSOCIATE,"Sacramento, CA",4.0,fun,a good place to work but the commission base c...,2019-10-14,7922,57817.0,NEGATIVE,0.888363,0.520140,0.519296,0.520552,0.518237
196,999995,Nordstrom,Cashier,"Braintree, MA",4.0,Well Grounded Staff,Everyone was very helpful and polite. Worked w...,2019-10-14,7922,57817.0,POSITIVE,0.999000,0.520972,0.523420,0.527086,0.524263
197,999996,Nordstrom,Sales Associate,"Thousand Oaks, CA",4.0,Company Needs A Facelift.,I love Nordstrom! Ask 15 year old me what my d...,2019-10-14,7922,57817.0,NEGATIVE,0.979740,0.534100,0.532903,0.534779,0.534719
198,999997,Nordstrom,Janitorial Worker,"Nashville, TN",4.0,I was not employed with Nordstrom through indeed,I was not employed with Nordstrom through inde...,2019-10-14,7922,57817.0,POSITIVE,0.999547,0.507829,0.507622,0.509452,0.510406
199,999998,Nordstrom,Warehouse Associate,"Elizabethtown, PA",2.0,Terrible Management!,Management is beyond terrible. They do not kno...,2019-10-14,7922,57817.0,POSITIVE,0.971467,0.510821,0.511463,0.511756,0.512086

In [11]:
df6=pd.read_csv("light-zero-shot/light-zero-shot-class-1000000.csv",header=None)
df6

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1000000,Nordstrom,Cosmetic Counter Manager/Freelance Make-up Art...,"Seattle, WA",4.0,Overall a pivotal part of shaping my life prof...,Almost 23 years spent with Nordstrom in many r...,2019-10-13,7922,57817.0,POSITIVE,0.999843,0.513767,0.516724,0.514931,0.515671
1,1000001,Nordstrom,Warehouse and shipping operator,"Elizabethtown, PA",5.0,Good,Very Good. I think that anyone who may go into...,2019-10-13,7922,57817.0,POSITIVE,0.999878,0.513125,0.516269,0.515121,0.514185
2,1000002,Nordstrom,Part Time On call Model,"Seattle, WA",5.0,Relaxed,Was a fun environment to work in! Flexible sch...,2019-10-13,7922,57817.0,POSITIVE,0.997554,0.509946,0.511894,0.511079,0.511348
3,1000003,Nordstrom,Server,"Anchorage, AK",4.0,Great place to work,I learned a lot working in the Nordstrom cafe....,2019-10-12,7922,57817.0,POSITIVE,0.999797,0.501717,0.509681,0.502700,0.504751
4,1000004,Nordstrom,Sales Representative,"Arlington, VA",5.0,Great learning experience,"Nordstrom provides a platform to grow, make go...",2019-10-12,7922,57817.0,POSITIVE,0.999540,0.508360,0.514237,0.509607,0.510937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377595,1377595,T-Mobile,Sales Associate,"Audubon, PA",1.0,Donâ€™t work for this company,"False promises, lies, was promised too grow qu...",2019-10-10,17874,91937.0,NEGATIVE,0.998813,0.511421,0.510885,0.510326,0.511627
377596,1377596,T-Mobile,CAS Customer Service,"Pueblo, CO",4.0,Good place for people to learn how to deal wit...,I am moving to a different state or I would st...,2019-10-10,10984,39087.0,POSITIVE,0.999780,0.493963,0.499164,0.495083,0.497228
377597,1377597,T-Mobile,CAS Customer Service,"Pueblo, CO",4.0,Good place for people to learn how to deal wit...,I am moving to a different state or I would st...,2019-10-10,17874,91937.0,POSITIVE,0.999780,0.493963,0.499164,0.495083,0.497228
377598,1377598,T-Mobile,T-Mobile Sales Representative,"Las Vegas, NV",5.0,learn about phones,learn how to handle phones how to reset them a...,2019-10-10,10984,39087.0,POSITIVE,0.999462,0.510988,0.513925,0.511701,0.513175
377599,1377599,T-Mobile,T-Mobile Sales Representative,"Las Vegas, NV",5.0,learn about phones,learn how to handle phones how to reset them a...,2019-10-10,17874,91937.0,POSITIVE,0.999462,0.510988,0.513925,0.511701,0.513175

In [12]:
df7=pd.read_csv("light-zero-shot/light-zero-shot-class-1377599.csv",header=None)
df7

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1377599,T-Mobile,T-Mobile Sales Representative,"Las Vegas, NV",5.0,learn about phones,learn how to handle phones how to reset them a...,2019-10-10,17874,91937.0,POSITIVE,0.999462,0.424373,0.427754,0.423825,0.422865
1,1377600,T-Mobile,Sale Representative,"Arlington, TX",4.0,Fun and friendly environment,Most days it was slow and not many people came...,2019-10-10,10984,39087.0,NEGATIVE,0.998905,0.442465,0.443581,0.442510,0.441447
2,1377601,T-Mobile,Sale Representative,"Arlington, TX",4.0,Fun and friendly environment,Most days it was slow and not many people came...,2019-10-10,17874,91937.0,NEGATIVE,0.998905,0.442465,0.443581,0.442510,0.441447
3,1377602,T-Mobile,Assistant Manager,"Dallas, OR",1.0,"Just donâ€™t, save the headache",This company is garbage and will make you feel...,2019-10-10,10984,39087.0,NEGATIVE,0.999519,0.432020,0.433332,0.432981,0.430986
4,1377603,T-Mobile,Assistant Manager,"Dallas, OR",1.0,"Just donâ€™t, save the headache",This company is garbage and will make you feel...,2019-10-10,17874,91937.0,NEGATIVE,0.999519,0.432020,0.433332,0.432981,0.430986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,1499994,Walmart,Customer Satisfaction Representative,"Bentonville, AR",3.0,Wal-Mart Account,I just worked on the Wal-Mart account. I reall...,2018-08-14,11259,55976.0,POSITIVE,0.999068,0.429004,0.430965,0.428509,0.426248
122396,1499995,Walmart,Deli Associate,"Carrollton, TX",5.0,Great!,"Walmart is a great place to work, it is fun an...",2018-08-14,11259,55976.0,POSITIVE,0.994319,0.428296,0.427720,0.427498,0.426381
122397,1499996,Walmart,Cart Pusher,"Mena, AR",4.0,Good place to start.,It is a great company to start at an entry lev...,2018-08-14,11259,55976.0,POSITIVE,0.999824,0.434120,0.434427,0.435659,0.434169
122398,1499997,Walmart,Produce Department Manager,"Wichita, KS",4.0,"Good Benefits, decent pay, overworked",I've worked for walmart several times at diffe...,2018-08-14,11259,55976.0,POSITIVE,0.999746,0.425161,0.428875,0.424603,0.424972
122399,1499998,Walmart,Unloader/Stocker,"Southport, NC",5.0,awesome place to work,i learned alot at walmart i met amazing people...,2018-08-14,11259,55976.0,POSITIVE,0.999726,0.420555,0.423012,0.422894,0.419453

In [13]:
df8=pd.read_csv("light-zero-shot/light-zero-shot-class-1500000.csv",header=None)
df8

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1500000,Walmart,Electronics Sales Associate,"Sandusky, MI",3.0,fun enviornment,"coworkers make the day go faster, easy work, c...",2018-08-14,11259,55976.0,NEGATIVE,0.910919,0.487315,0.489250,0.486242,0.488310
1,1500001,Walmart,STORE ASSOCIATE,"Brownsville, TX",4.0,It was aight,Definitely the highest paying job to start off...,2018-08-14,11259,55976.0,POSITIVE,0.999561,0.487432,0.489165,0.488381,0.487759
2,1500002,Walmart,Electronic Sales Associate,"El Campo, TX",4.0,Walmart,Walmart is a general large company. Its a fair...,2018-08-14,11259,55976.0,POSITIVE,0.809016,0.487445,0.486389,0.485733,0.486025
3,1500003,Walmart,Stocker,"Columbus, OH",3.0,Fun sometimes great,Employees are sometime great and nice and frie...,2018-08-14,11259,55976.0,POSITIVE,0.999531,0.488799,0.491567,0.487702,0.488197
4,1500004,Walmart,Deli Associate,"Hickory Creek, TX",1.0,nope,"no hours, low pay and incompetent managers. It...",2018-08-14,11259,55976.0,NEGATIVE,0.996703,0.487918,0.488395,0.487368,0.487928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178395,1678395,Xerox,Client Site Coordinator,"Austin, TX",4.0,Stable company but gets somewhat compartmental...,"Very stable, friendly and open company. There...",2017-07-16,11636,27983.0,POSITIVE,0.998559,0.498098,0.498986,0.494731,0.497223
178396,1678396,Xerox,Contract Manager,United States,3.0,Great opportunities to work remotely,"Xerox is a very large company, but in spite of...",2017-07-16,11636,27983.0,POSITIVE,0.999780,0.491089,0.493279,0.489223,0.489933
178397,1678397,Xerox,Benefits Specialist,"Cherry Hill, NJ",3.0,not bad for the money,the benefits are not bad but too many people c...,2017-07-16,11636,27983.0,NEGATIVE,0.625495,0.495680,0.493151,0.491968,0.492704
178398,1678398,Xerox,Customer Care,"Madison, MS",4.0,It Depends,This is cool job to work. Great Pay and Flexib...,2017-07-15,11636,27983.0,POSITIVE,0.508201,0.485137,0.485389,0.486340,0.486076
178399,1678399,Xerox,"Head & Ink Operator III, Batching & Congealing","Wilsonville, OR",4.0,Diversified work environment,"Numerous job classifications, which enable one...",2017-07-15,11636,27983.0,POSITIVE,0.896202,0.493003,0.491835,0.488811,0.492134

In [14]:
df9=pd.read_csv("light-zero-shot/light-zero-shot-class-1678399.csv",header=None)
df9

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1678399,Xerox,"Head & Ink Operator III, Batching & Congealing","Wilsonville, OR",4.0,Diversified work environment,"Numerous job classifications, which enable one...",2017-07-15,11636,27983.0,POSITIVE,0.896202,0.468098,0.467934,0.465335,0.467749
1,1678400,Xerox,MAIL OFFICER,Washington DC,4.0,Very neat and organized,Mail officer from july 2002 to may 2004. As a ...,2017-07-15,11636,27983.0,NEGATIVE,0.979352,0.462126,0.456014,0.458859,0.459360
2,1678401,Xerox,Member Services Representative,"Charlotte, NC",4.0,Job was,This company was very a great leaning experien...,2017-07-15,11636,27983.0,POSITIVE,0.998355,0.461566,0.459403,0.461423,0.462717
3,1678402,Xerox,Courier/ warehouse associate,"Austin, TX",4.0,Productive and fun to work for,"I enjoy working for Xerox, it's a great work e...",2017-07-15,11636,27983.0,POSITIVE,0.999843,0.469830,0.470910,0.471221,0.471203
4,1678403,Xerox,Manager,NY,1.0,Conduent: Fire Fighting is a way of life,Conduent: This is at the executive level... Li...,2017-07-15,11636,27983.0,NEGATIVE,0.997613,0.459291,0.454415,0.457791,0.459710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214795,1893194,Starbucks,Starbucks Shift Supervisor,"Bend, OR",2.0,Summary,"The management issues in Bend, Oregon are very...",2018-09-24,25434,77702.0,NEGATIVE,0.999289,0.460610,0.460338,0.461388,0.460542
214796,1893195,Starbucks,Barista,"Pikesville, MD",3.0,"Team is friendly, helpful, and passionate",A fast-paced work environment. Drinks are easy...,2018-09-24,25434,77702.0,POSITIVE,0.999876,0.477013,0.476151,0.477575,0.476970
214797,1893196,Starbucks,Barista,"Phoenix, AZ",5.0,starbucks is a fun job,great for students and people who just need so...,2018-09-24,25434,77702.0,NEGATIVE,0.992694,0.466538,0.463343,0.463540,0.464499
214798,1893197,Starbucks,Cashier/barista,"Schertz, TX 78154",4.0,Excellent benefits,The benefits were the best benefits any compan...,2018-09-24,25434,77702.0,POSITIVE,0.999714,0.471761,0.470962,0.471333,0.471793
214799,1893198,Starbucks,Barista,"Wilmington, NC",5.0,Good place to work,"starbucks is a wonderful place to work, I love...",2018-09-24,25434,77702.0,POSITIVE,0.999883,0.468080,0.472662,0.471291,0.470452

In [15]:
df10=pd.read_csv("light-zero-shot/light-zero-shot-class-1893198.csv",header=None)
df10

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1893198,Starbucks,Barista,"Wilmington, NC",5.0,Good place to work,"starbucks is a wonderful place to work, I love...",2018-09-24,25434,77702.0,POSITIVE,0.999883,0.465848,0.463206,0.464266,0.465077
1,1893199,Starbucks,Barista and Cashier,"Columbus, OH",4.0,Wasn't too bad I just don't like coffee,Super busy day starting from 430am until midni...,2018-09-24,25434,77702.0,POSITIVE,0.985019,0.456868,0.453721,0.457640,0.456916
2,1893200,Starbucks,Barista/Cashier,"West Haven, CT",2.0,Ehh,"Don't work at Starbucks, but if you like under...",2018-09-24,25434,77702.0,POSITIVE,0.963652,0.469373,0.469167,0.469200,0.469668
3,1893201,Starbucks,Barista,"Jacksonville, FL",4.0,Just another job,It paid the bills a little bit. Got to experie...,2018-09-23,25434,77702.0,POSITIVE,0.998430,0.457248,0.455397,0.456900,0.456601
4,1893202,Starbucks,Barista,"West Caldwell, NJ",5.0,Great Place to Work,I loved my team working at Starbucks. It's bec...,2018-09-23,25434,77702.0,POSITIVE,0.999762,0.460374,0.457439,0.459869,0.459717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106795,1999993,Eastman Chemical,Hydroblasting Technician,"Kingsport, TN",3.0,Long hours bad work life balance,Great pay but long hours bad work life balance...,2021-02-26,29392,80080.0,NEGATIVE,0.991889,0.466674,0.464770,0.468055,0.467121
106796,1999994,Eastman Chemical,Sleep Technician,"Martinsville, VA",3.0,Have to know the right people to advance,There is alot of current people that still wor...,2021-02-17,29392,80080.0,NEGATIVE,0.885353,0.475974,0.474047,0.474414,0.475987
106797,1999995,Eastman Chemical,Process Operator,"Longview, TX",3.0,Doesnâ€™t really care about employees,Itâ€™s evident that this company operates on a t...,2021-02-10,29392,80080.0,NEGATIVE,0.996352,0.481769,0.481297,0.480902,0.482099
106798,1999996,Eastman Chemical,Machine Operator,"Collinsville, VA",2.0,"Excessive overtime, Biased management",There is very little opportunity for advanceme...,2021-01-27,29392,80080.0,NEGATIVE,0.999548,0.480837,0.478567,0.480972,0.479469
106799,1999997,Eastman Chemical,Sales,Remote,2.0,Good place to work if you can deal with endles...,"The culture is built upon checking off boxes, ...",2021-01-21,29392,80080.0,POSITIVE,0.517432,0.466944,0.466332,0.467053,0.467480

In [16]:
df11=pd.read_csv("light-zero-shot/light-zero-shot-class-2000000.csv",header=None)
df11

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,2000000,Eastman Chemical,E&I Technician,Texas,4.0,Overall a great job,4/10 work scheduleOvertime often available but...,2020-12-31,29392,80080.0,POSITIVE,0.990666,0.565419,0.564274,0.567126,0.570171
1,2000001,Eastman Chemical,LSE,"Kingsport, TN",3.0,Good place if you have 11 bracket job.,They need to throw the ACT workkeys testing th...,2020-12-24,29392,80080.0,NEGATIVE,0.992698,0.556512,0.558135,0.558732,0.559917
2,2000002,Eastman Chemical,Lab technician,"Gray, TN",3.0,Good old boy network,Horrible. There are some really good people. B...,2020-12-23,29392,80080.0,NEGATIVE,0.998872,0.550529,0.550079,0.554955,0.558614
3,2000003,Eastman Chemical,Automation Engineer,"Ghent, MN",3.0,Dynamic working environment,"Work it's well paid, benefits and compensation...",2020-12-10,29392,80080.0,POSITIVE,0.998360,0.552532,0.554240,0.555063,0.557618
4,2000004,Eastman Chemical,Operator in Oxo Aldehyde Operations,"Longview, TX",2.0,Stressful p,Used to be a great company to work for. All th...,2020-12-04,29392,80080.0,NEGATIVE,0.997070,0.545078,0.545931,0.546934,0.550550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328195,2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734
328196,2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166
328197,2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586
328198,2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244
328199,2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050

In [28]:
final_df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11],ignore_index=True)
final_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936
1,1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430
2,2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410
3,3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765
4,4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734
2328196,2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166
2328197,2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586
2328198,2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244
2328199,2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050

In [29]:
final_df=final_df[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]
final_df

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936
1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430
2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410
3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765
4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050

In [30]:
final_df.columns=['company_name', 'position', 'location', 'rate', 'review_title',
       'review_content', 'review_date', 'gvkey', 'permno',
       'review_sentiment_label', 'review_sentiment_score', 'culture',
       'compensation', 'work life balance', 'career opportunity']

In [31]:
final_df

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity
0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936
1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430
2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410
3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765
4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050

In [32]:
final_df.to_csv("final_zero_shot.csv",index=False)

In [34]:
pd.read_csv("final_zero_shot.csv")

,company_name,position,location,rate,review_title,review_content,review_date,gvkey,permno,review_sentiment_label,review_sentiment_score,culture,compensation,work life balance,career opportunity
0,American Airlines,Software Developer,"Fort Worth, TX",4.0,all new tech and free flight benefits,overall a good company to work for. work cultu...,2022-01-26,1045,21020.0,POSITIVE,0.999854,0.471023,0.471894,0.472492,0.472936
1,American Airlines,Customer Service Representative,"Philadelphia, PA",3.0,Great job to have in the tuck.,Amazing travel benefits. Can make your own sch...,2022-01-25,1045,21020.0,POSITIVE,0.999723,0.481977,0.484626,0.481891,0.483430
2,American Airlines,Reservations Agent,"Fort Worth, TX",3.0,It's a call center job,"Lots of micromangement, mandatory overtime and...",2022-01-24,1045,21020.0,NEGATIVE,0.976279,0.477675,0.481417,0.478622,0.481410
3,American Airlines,Customer Service Representative,"Arlington, VA",5.0,N/a,Great place to work. life/balance. flexible wo...,2022-01-24,1045,21020.0,POSITIVE,0.999861,0.472097,0.474614,0.473281,0.475765
4,American Airlines,Customer Service Representative,"Austin, TX",4.0,The flight benefits are great but you work hol...,I loved that everyday you see something new on...,2022-01-23,1045,21020.0,POSITIVE,0.999312,0.482435,0.485841,0.485259,0.486576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2328195,LyondellBasell,Customer Service Representative,"Lansing, MI",5.0,Fast past,Lyondel Bassell is a great company. It is very...,2014-11-16,294524,12345.0,POSITIVE,0.999828,0.551957,0.551629,0.551767,0.554734
2328196,LyondellBasell,"Lead, Customer Solutions Supply Chain","Houston, TX",5.0,Great place to work,Nice group of people who really care about the...,2014-11-04,294524,12345.0,POSITIVE,0.999744,0.559295,0.558944,0.562894,0.568166
2328197,LyondellBasell,Analytical Chemist/Assistant Lab Supervisor,"Pasadena, TX",5.0,Excellent Company,Excellent Company with competitive salary and ...,2014-11-04,294524,12345.0,POSITIVE,0.999869,0.562636,0.562568,0.566505,0.569586
2328198,LyondellBasell,Quality Control Laboratory Technician,"Jackson, TN",4.0,it was an overall good place to work.,Lyondell-Basell was a good place to work for a...,2014-11-03,294524,12345.0,NEGATIVE,0.993195,0.539485,0.542651,0.544064,0.550244
2328199,LyondellBasell,Lab Technician,"Houston, TX",5.0,job,good place to work and fun environment. I was ...,2014-10-30,294524,12345.0,POSITIVE,0.999855,0.540879,0.543901,0.545580,0.550050